---
services:
# Main Bot Container
  discord-bot:
    image: ghcr.io/malavisto/anilist-randomizer-discord:main
    build: .  #Uncomment to build image locally instead
    container_name: anilist-discord-bot
    networks:
      - services
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true
    environment:
      - TZ=$TimeZone
      - DISCORD_TOKEN=$DISCORD_TOKEN
      - METRICS_PORT=9090      
    volumes:
      - ./logs:/usr/src/app/logs
    env_file: .env   
#    ports:     # Uncomment if prometheus is hosted externaly
#      - 9090:9090
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Watchtower for auto updates
  watchtower:
      image: containrrr/watchtower
      environment:
        - TZ=$TimeZone
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_LABEL_ENABLE=true
      restart: unless-stopped  
      networks:
        - services  
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      command: --interval 30

# Prometheus for metrics scraping
  prometheus:  # Check https://github.com/Malavisto/anilist-randomizer-discord/tree/main/prometheus for more info
    image: prom/prometheus
    container_name: anilist-prometheus
    networks:
      - services
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    depends_on:
      - discord-bot

networks:
  services:
    external: true
