---
services:
  discord-bot:
    image: ghcr.io/malavisto/anilist-randomizer-discord:main
#    build: .  #Uncomment to build image locally instead
    container_name: anilist-discord-bot
    networks:
      - services
    restart: unless-stopped
    environment:
      - TZ=$TimeZone
      - DISCORD_TOKEN=$DISCORD_TOKEN
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_SECRET=$CLIENT_SECRET
      - METRICS_PORT=9093      
    volumes:
      - ./logs:/usr/src/app/logs
    env_file: .env   
    ports:
      - 9093:9093
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


# Prometheus setup for new setups

#  prometheus:
#    image: prom/prometheus
#    container_name: anilist-prometheus
#    networks:
#      - services
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - "9091:9090"
#    depends_on:
#      - discord-bot        

networks:
  services:
    external: true
